name: Build Go

on:
  push:
    branches:
      - cn
  pull_request:
    branches:
      - cn
  workflow_dispatch:
    inputs:
      reason:
        description: '运行原因'
        required: false
        default: '手动触发构建'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:

  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Build
        run: |
          cd go
          go build -buildmode=c-shared -ldflags="-s -w" -trimpath -o libmtorrentserver.so ./binding/desktop
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: libmtorrentserver-linux
          path: go/libmtorrentserver.*

  build-for-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Build
        run: |
          cd go
          go build -buildmode=c-shared -ldflags="-s -w" -trimpath -o libmtorrentserver.dylib ./binding/desktop
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: libmtorrentserver-macos
          path: go/libmtorrentserver.*

  build-for-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Build
        run: |
          cd go
          go build -buildmode=c-shared -ldflags="-s -w" -trimpath -o libmtorrentserver.dll ./binding/desktop
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: libmtorrentserver-windows
          path: go/libmtorrentserver.*
