name: Build Go

on:
  push:
    branches:
      - cn
  pull_request:
    branches:
      - cn
  workflow_dispatch:
    inputs:
      reason:
        description: '运行原因'
        required: false
        default: '手动触发构建'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Build
        run: 
            cd go
            go build -buildmode=c-shared -ldflags="-s -w" -trimpath -o libmtorrentserver.so ./binding/desktop
            mv libmtorrentserver.so libmtorrentserver.linux.so
            mv libmtorrentserver.h libmtorrentserver.linux.h
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:          
          path: libmtorrentserver.*
